name: leetcoder auto download
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  leetcoder-download:
    runs-on: leetcoder:latest
    env:
      LEETCODE_COOKIE: ${{ secrets.LEETCODE_COOKIE }}
      DOWNLOAD_FOLDER: './'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      - name: Install leetcoder
        run: gem install leetcoder

      - name: Download Submissions
        run: leetcode -d all -f $DOWNLOAD_FOLDER

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'leetcoder: updated leetcode submissions'
          commit_user_email: leetcoder+github-actions[bot]@users.noreply.github.com
          commit_author:  Name <your-name@email.address>