name: Build leetcoder
on:
  push:
    branches:
      - main
      - release/**

jobs:
  leetcoder-download:
    runs-on: ubuntu-latest
    env:
      LEETCODE_COOKIE: ${{ secrets.LEETCODE_COOKIE }}
      DOWNLOAD_FOLDER: './leetcode'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      - name: Build Gem
        run: gem build leetcoder.gemspec

      - name: Install leetcoder
        run: gem install leetcoder-*?.gem

      - name: Download Submissions
        run: leetcoder -d all -f $DOWNLOAD_FOLDER
