name: Leetcoder CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.1'

    env:
      TEST: 'true'
      LEETCODE_COOKIE: 'csrftoken=4aB9fJwE3hxkolwtcZo; LEETCODE_SESSION=dskjflskjfk;'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Specs
        run: bundle exec rspec
      - name: Run RuboCop
        run: bundle exec rubocop --config .rubocop.yml --parallel
